name: update_readme_table

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  update_readme_table:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync

      - name: run script
        run: |
          git status
          git pull origin main
          uv run "./src/pepy_tech_stats/__main__.py" --api-key ${{ secrets.API_KEY }}

      - name: Checkout branch
        run: |
          git fetch origin main
          git checkout main
          git pull origin main

      - name: commit and push data
        env:
          CI_COMMIT_MESSAGE: "run: update readme table"
          CI_COMMIT_AUTHOR: table_update
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git status
          git add data
          if ! git diff --cached --quiet; then
            git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main
          else
            echo "No changes to commit"
          fi