name: update_readme_table
on:
  workflow_dispatch:
  schedule:
  - cron: 0 13 * * *
jobs:
  update_readme_table:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: install rust
      uses: dtolnay/rust-toolchain@stable
    - name: Cache cargo deps
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache target/release build
      id: release-cache
      uses: actions/cache@v4
      with:
        path: target/release
        key: ${{ runner.os }}-cargo-target-release-${{ hashFiles('**/Cargo.lock') }}
    - name: Build release version
      if: steps.release-cache.outputs.cache-hit != 'true'
      run: cargo build --release
    - name: Run binary
      run: './target/release/pepy-tech-stats --api-key ${{ secrets.API_KEY }}'
    - name: commit and push data
      env:
        CI_COMMIT_MESSAGE: 'run: update readme table'
        CI_COMMIT_AUTHOR: table_update
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git status
          git add README.md
          if ! git diff --cached --quiet; then
            git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main
          else
            echo "No changes to commit"
          fi
